"""v2 Kernel 核心契约（Phase 1 填充完成，P1-T06 re-export 收尾）。

职责：单一 authoritative state 的数据语言——Entity / typed Component、
WorldState / RuntimeState 分离、Revision、Action（Registry / Proposal /
Lifecycle）、ProposedEffect、Authority、Validation、Conflict Resolution、
Transaction / Reducer、DomainEvent（含 provenance）。

对应 Spec 章节：§4 Kernel 强制不变量（K1–K8）、§8 State Model、
§9 Revision Model、§10 Entity / Component Contract、§11 Action Contract、
§16 Effect Contract、§17 Authority Contract、§18 Effect Validation、
§19 Conflict Resolution、§20 Transaction / Reducer、§21 Event Contract。

此包禁止 import LangGraph / OpenAI（G1 门禁），且完全不接 LLM（Spec §47
Phase 1 验收：core tests 无网络、无 LLM 可完整运行）。

re-export 收尾（设计文档 §0.4）：P1 全部契约模块的公共导出集中于此——
从各模块 import 再导出并定义 ``__all__``（骨架期"__init__.py 仅 docstring"
纪律的预告解除，``tests/test_engine_v2_skeleton.py`` 已同步最小修订为仅
允许本文件的 re-export 语句与 ``__all__`` 清单）。契约类型一律以
``from src.engine_v2.core import <类型>`` 直接可用；各名称的**定义来源
保持单一**（``CONTRACT_SCHEMA_VERSION`` 只从 ``state.py`` 导入——T02
已确立其为唯一定义源，``snapshot.py`` 亦从 ``state.py`` 复用，严禁双源
复写）。

**同名遮蔽豁免（机械规则，非裁剪）**：与**子模块同名**的模块导出不在
包级 re-export——本包中即 ``snapshot.py`` 的 ``snapshot()`` 纯函数与
``snapshot`` 子模块同名：若把函数绑到包属性 ``core.snapshot``，会覆盖
import 系统在该子模块加载时设置的同名模块属性，使
``import src.engine_v2.core.snapshot as m``（bpo-30024：属性链成功时
不回退 sys.modules）拿到函数而非模块，破坏既有测试对子模块的访问。
故 ``snapshot()`` 仅经子模块路径导出（``from src.engine_v2.core.snapshot
import snapshot``）；包属性 ``core.snapshot`` 保持为子模块。该规则由
``tests/engine_v2/core/test_closeout.py`` 机械化断言（与子模块名撞名的
导出集合必须恰为豁免集合）。

P2 行为模块 re-export（D-P2-19 / P2 设计规范 §10.2/§10.3）：各 P2 任务包
按 §10.2 顺序在本文件追加本模块 re-export 块与 ``__all__`` 条目（字母序
插入，P1 同款纪律）。当前已含 ``authority``（P2-T02/T03）、``reducer``
（P2-T01）、``transaction_executor``（P2-T06）、``validation``（P2-T04）、
``conflicts``（P2-T05）与 ``cascade``（P2-T07/T08：级联执行器 + 触发器 +
深度/环路熔断）六个导出块。
P3 编排层模块 re-export（P3 设计规范 §3.11 / D-P3-12 机械同步）：新增
7 个模块 action_lifecycle / action_registry / clock / event_queue /
interrupt / revalidation / scheduler 的 re-export 块与 __all__ 条目按
字母序插入（53 项，196 → 249）；test_closeout.py 的
_CORE_SUBMODULE_NAMES（19 → 26）与规模锚点（249）、
test_import_boundary.py 的 CORE_SUBMODULES（26）已同步。

"""

from src.engine_v2.core.action_lifecycle import (
    abort_action,
    apply_checkpoint,
    complete_action,
    fail_action,
    IllegalTransitionError,
    LIFECYCLE_TRANSITIONS,
    LifecycleEvent,
    LifecycleTransition,
    progress_of,
    resume_action,
    transition_action,
)
from src.engine_v2.core.action_registry import (
    ActionRegistry,
    ActionSpec,
    DurationPolicy,
    PARAMETER_TYPES,
    ParameterSpec,
    UnknownActionError,
    validate_timing,
)
from src.engine_v2.core.actions import (
    ACTION_TYPE_ID_PATTERN,
    ActionLifecycleStatus,
    ActionProposal,
    ActionTiming,
    ActionTypeId,
    ActiveAction,
    FallbackSpec,
    parse_action_type_id,
)
from src.engine_v2.core.authority import (
    AUTHORITY_REASON_CODES,
    AuthorityDecision,
    AuthorityError,
    AuthorityEvaluationResult,
    AuthorityPolicy,
    AuthorityRule,
    AuthoritySelector,
    KERNEL_STATE_DOMAINS,
    ProducerConflictError,
    ProducerInfo,
    ProducerRegistry,
    check_authority,
    match_selector,
)
from src.engine_v2.core.behavior_policy import (
    BehaviorPolicy,
    PlayerPolicy,
    run_policy_decide,
    PolicyActorMismatchError,
)
from src.engine_v2.core.capability import (
    Capability,
    CapabilityGrant,
    CapabilityTable,
    check_capability,
    DEFAULT_NPC_CAPABILITIES,
    CapabilityScopeError,
)
from src.engine_v2.core.clock import (
    ClockRollbackError,
    LogicalClock,
    next_due_tick,
    rebuild_runtime,
    SchedulerError,
    set_logical_tick,
)
from src.engine_v2.core.components import (
    COMPONENT_TYPE_ID_PATTERN,
    ComponentConflictError,
    ComponentData,
    ComponentRegistry,
    ComponentSchema,
    ComponentTypeId,
    parse_component_type_id,
)
from src.engine_v2.core.cascade import (
    CASCADE_DIAGNOSTIC_KINDS,
    CascadeConfig,
    CascadeCycleError,
    CascadeDepthExceededError,
    CascadeDiagnostic,
    CascadeError,
    CascadeExecutionResult,
    CascadeExecutor,
    CascadeResult,
    CascadeStatistics,
    CascadeTrigger,
    CascadeTriggerRegistry,
    CycleDetector,
    CycleHit,
    DEFAULT_MAX_CASCADE_DEPTH,
    SyncTrigger,
    TriggerConflictError,
    TriggerRegistry,
)
from src.engine_v2.core.conflicts import (
    AuthorityPriorityStrategy,
    ConflictAction,
    ConflictError,
    ConflictGroup,
    ConflictKey,
    ConflictResolution,
    ConflictResolutionReport,
    ConflictStrategy,
    DEFAULT_STRATEGIES,
    DefaultConflictResolver,
    DomainResolverFactory,
    EntityFifoStrategy,
    ProducerPriorityStrategy,
    ResolutionContext,
    TIMESTAMP_METADATA_KEY,
    TimestampStrategy,
    conflict_key,
    conflicts_with,
    detect_conflicts,
    effect_locks,
    extract_effect_locks,
    resolve_conflicts,
)
from src.engine_v2.core.context_provider import (
    ContextBuildInput,
    ActorDecisionContext,
    ContextProvider,
    DefaultContextProvider,
    ActorUnknownError,
    ContextInvariantError,
)
from src.engine_v2.core.effects import (
    EFFECT_TYPE_ID_PATTERN,
    STATE_DOMAIN_ID_PATTERN,
    CommittedEffect,
    EffectTarget,
    EffectTypeId,
    EntityTarget,
    ProposedEffect,
    StateDomainId,
    StateDomainTarget,
    parse_effect_type_id,
    parse_state_domain_id,
)
from src.engine_v2.core.entity import ContractModel, EntityRecord, EntityRef, EntityView
from src.engine_v2.core.event_queue import (
    enqueue_scheduled_event,
    make_scheduled_event,
    QueueInvariantError,
    SCHEDULED_EVENT_KINDS,
    take_due,
)
from src.engine_v2.core.events import (
    EVENT_TYPE_ID_PATTERN,
    DomainEvent,
    EventTypeId,
    parse_event_type_id,
)
from src.engine_v2.core.gameplay_mode import (
    ModeOperationKind,
    ModeOperation,
    ModeOverlay,
    ModeOverlayRegistry,
    MergedModeConfiguration,
    merge_modes,
    is_action_available,
    ModeInvariantError,
    ModeChangeRequest,
    ModeChangeResolution,
    ModePolicy,
    DefaultModePolicy,
    apply_mode_change,
    UnknownModeError,
)
from src.engine_v2.core.ids import (
    FACTORY_BODY_PATTERN,
    PREFIX_BODY_PATTERN,
    PREFIX_TO_KIND,
    PRODUCER_ID_PATTERN,
    ActionInstanceId,
    CascadeId,
    EffectId,
    EntityId,
    EventId,
    ObservationId,
    ProducerId,
    ScheduledEntryId,
    TraceRecordId,
    TransactionId,
    new_action_instance_id,
    new_cascade_id,
    new_effect_id,
    new_entity_id,
    new_event_id,
    new_observation_id,
    new_scheduled_entry_id,
    new_trace_record_id,
    new_transaction_id,
    parse_id,
)
from src.engine_v2.core.interrupt import (
    BoundaryReport,
    BUILTIN_CONDITION_RESOLVERS,
    CONDITION_KINDS,
    ConditionResolver,
    ConditionResolverRegistry,
    DecisionBoundary,
    evaluate_boundaries,
    evaluate_condition,
    InterruptCondition,
    UnknownConditionError,
)
from src.engine_v2.core.knowledge import (
    BeliefKind,
    Belief,
    KnowledgeState,
    ObservationRecord,
    OBSERVATIONS_COMPONENT,
    KNOWLEDGE_COMPONENT,
    MEMORY_COMPONENT,
    encode_observations,
    decode_observations,
    encode_knowledge,
    decode_knowledge,
)
from src.engine_v2.core.provenance import (
    CascadeContext,
    CauseKind,
    CauseRef,
    OriginKind,
    Provenance,
)
from src.engine_v2.core.reducer import (
    CreateEntityPayload,
    EFFECT_CREATE_ENTITY,
    EFFECT_REMOVE_COMPONENT,
    EFFECT_REMOVE_ENTITY,
    EFFECT_REMOVE_WORLD_VARIABLE,
    EFFECT_SET_COMPONENT,
    EFFECT_SET_SCENARIO_DATA,
    EFFECT_SET_WORLD_VARIABLE,
    EffectApplicationError,
    EffectHandler,
    EffectHandlerRegistry,
    EmptyPayload,
    GuardedWorldState,
    HandlerConflictError,
    ReducerError,
    RemoveWorldVariablePayload,
    SetScenarioDataPayload,
    SetWorldVariablePayload,
    STRUCTURAL_EFFECT_TYPES,
    WriteBarrier,
    WriteBarrierError,
    apply_committed_effects,
    apply_transaction,
    default_handler_registry,
    guard,
    install_write_barrier,
    is_guarded,
    state_create_entity,
    state_remove_component,
    state_remove_entity,
    state_remove_world_variable,
    state_set_component,
    state_set_scenario_state,
    state_set_world_variable,
    uninstall_write_barrier,
    write_barrier_exempt,
    write_barrier_installed,
)
from src.engine_v2.core.revalidation import (
    rebase_proposal,
    revalidate_proposal,
    RevalidationDecision,
)
from src.engine_v2.core.revision import (
    INITIAL_WORLD_REVISION,
    RevalidationOutcome,
    Revision,
    is_stale,
    next_revision,
)
from src.engine_v2.core.scheduler import (
    enqueue_actor_wakeup,
    PauseReason,
    Scheduler,
    scheduler_fingerprint,
    SchedulerConfigurationError,
    SchedulerOutcome,
    SchedulerWakeupError,
    start_action,
    TimePolicy,
    WakeupHook,
    WakeupHookRegistry,
)
from src.engine_v2.core.serialization import (
    assert_json_clean,
    deep_copy_via_roundtrip,
    dump_json,
    load_json,
)
# 注意：snapshot.py 的 ``snapshot()`` 纯函数**不**在包级 re-export——与
# ``snapshot`` 子模块同名，函数绑到包属性会遮蔽子模块属性（模块 docstring
# "同名遮蔽豁免"）；经 ``src.engine_v2.core.snapshot.snapshot`` 可达。
from src.engine_v2.core.snapshot import (
    SNAPSHOT_FORMAT_VERSION,
    Snapshot,
    check_snapshot_versions,
    freeze_view,
    restore_snapshot,
)
from src.engine_v2.core.space import (
    SPATIAL_BACKEND_KINDS,
    SpatialDomain,
    SpaceBackend,
    INF_DISTANCE,
    SpaceRegistry,
    make_backend,
    UnknownDomainError,
    UnknownBackendError,
    InvalidPositionError,
    SpaceInvariantError,
    SpacePosition,
    GraphSpace,
    GridSpace,
    SpaceMapping,
    SPACES_COMPONENT,
    encode_spaces,
    decode_spaces,
    entity_domain_positions,
)
from src.engine_v2.core.state import (
    CONTRACT_SCHEMA_VERSION,
    ActorWakeup,
    BackendStateRef,
    RngState,
    RuntimeLifecycle,
    RuntimeState,
    ScenarioState,
    ScheduledEvent,
    WorldState,
)
from src.engine_v2.core.trace import (
    DECISION_PAYLOAD_KEYS,
    LLM_CALL_PAYLOAD_KEYS,
    PAYLOAD_RECORD_KEY,
    TraceKind,
    TraceRecord,
)
from src.engine_v2.core.transaction import Transaction, TransactionStatus
from src.engine_v2.core.transaction_executor import abort_transaction, commit_transaction
from src.engine_v2.core.validation import (
    EffectValidator,
    TRANSACTION_REFERENCE_ISSUE_KINDS,
    VALIDATION_ISSUE_KINDS,
    ValidationError,
    ValidationContext,
    ValidationIssue,
    ValidationPipeline,
    ValidationReport,
    check_effect_id_kinds,
    check_transaction_references,
    validate_proposed_effect,
)

__all__ = [
    'abort_action',
    'ACTION_TYPE_ID_PATTERN',
    'ActionInstanceId',
    'ActionLifecycleStatus',
    'ActionProposal',
    'ActionRegistry',
    'ActionSpec',
    'ActionTiming',
    'ActionTypeId',
    'ActiveAction',
    'ActorWakeup',
    'apply_checkpoint',
    'AUTHORITY_REASON_CODES',
    'AuthorityDecision',
    'AuthorityError',
    'AuthorityEvaluationResult',
    'AuthorityPolicy',
    'AuthorityPriorityStrategy',
    'AuthorityRule',
    'AuthoritySelector',
    'BackendStateRef',
    'BoundaryReport',
    'BUILTIN_CONDITION_RESOLVERS',
    'CASCADE_DIAGNOSTIC_KINDS',
    'ClockRollbackError',
    'complete_action',
    'COMPONENT_TYPE_ID_PATTERN',
    'CONDITION_KINDS',
    'ConditionResolver',
    'ConditionResolverRegistry',
    'CONTRACT_SCHEMA_VERSION',
    'CascadeConfig',
    'CascadeContext',
    'CascadeCycleError',
    'CascadeDepthExceededError',
    'CascadeDiagnostic',
    'CascadeError',
    'CascadeExecutionResult',
    'CascadeExecutor',
    'CascadeId',
    'CascadeResult',
    'CascadeStatistics',
    'CascadeTrigger',
    'CascadeTriggerRegistry',
    'CauseKind',
    'CauseRef',
    'CommittedEffect',
    'ComponentConflictError',
    'ComponentData',
    'ComponentRegistry',
    'ComponentSchema',
    'ComponentTypeId',
    'ConflictAction',
    'ConflictError',
    'ConflictGroup',
    'ConflictKey',
    'ConflictResolution',
    'ConflictResolutionReport',
    'ConflictStrategy',
    'ContractModel',
    'CreateEntityPayload',
    'CycleDetector',
    'CycleHit',
    'DECISION_PAYLOAD_KEYS',
    'DecisionBoundary',
    'DEFAULT_MAX_CASCADE_DEPTH',
    'DEFAULT_STRATEGIES',
    'DefaultConflictResolver',
    'DomainEvent',
    'DomainResolverFactory',
    'DurationPolicy',
    'EFFECT_CREATE_ENTITY',
    'EFFECT_REMOVE_COMPONENT',
    'EFFECT_REMOVE_ENTITY',
    'EFFECT_REMOVE_WORLD_VARIABLE',
    'EFFECT_SET_COMPONENT',
    'EFFECT_SET_SCENARIO_DATA',
    'EFFECT_SET_WORLD_VARIABLE',
    'EFFECT_TYPE_ID_PATTERN',
    'enqueue_actor_wakeup',
    'enqueue_scheduled_event',
    'evaluate_boundaries',
    'evaluate_condition',
    'EVENT_TYPE_ID_PATTERN',
    'EffectApplicationError',
    'EffectHandler',
    'EffectHandlerRegistry',
    'EffectId',
    'EffectTarget',
    'EffectTypeId',
    'EffectValidator',
    'EmptyPayload',
    'EntityFifoStrategy',
    'EntityId',
    'EntityRecord',
    'EntityRef',
    'EntityTarget',
    'EntityView',
    'EventId',
    'EventTypeId',
    'FACTORY_BODY_PATTERN',
    'fail_action',
    'FallbackSpec',
    'GuardedWorldState',
    'HandlerConflictError',
    'IllegalTransitionError',
    'INITIAL_WORLD_REVISION',
    'InterruptCondition',
    'KERNEL_STATE_DOMAINS',
    'LIFECYCLE_TRANSITIONS',
    'LifecycleEvent',
    'LifecycleTransition',
    'LLM_CALL_PAYLOAD_KEYS',
    'LogicalClock',
    'make_scheduled_event',
    'next_due_tick',
    'ObservationId',
    'OriginKind',
    'PARAMETER_TYPES',
    'ParameterSpec',
    'PauseReason',
    'PAYLOAD_RECORD_KEY',
    'PREFIX_BODY_PATTERN',
    'PREFIX_TO_KIND',
    'PRODUCER_ID_PATTERN',
    'ProducerConflictError',
    'ProducerId',
    'ProducerInfo',
    'ProducerPriorityStrategy',
    'ProducerRegistry',
    'progress_of',
    'ProposedEffect',
    'Provenance',
    'QueueInvariantError',
    'rebase_proposal',
    'rebuild_runtime',
    'ReducerError',
    'RemoveWorldVariablePayload',
    'ResolutionContext',
    'resume_action',
    'revalidate_proposal',
    'RevalidationDecision',
    'RevalidationOutcome',
    'Revision',
    'RngState',
    'RuntimeLifecycle',
    'RuntimeState',
    'SCHEDULED_EVENT_KINDS',
    'Scheduler',
    'scheduler_fingerprint',
    'SchedulerConfigurationError',
    'SchedulerError',
    'SchedulerOutcome',
    'SchedulerWakeupError',
    'set_logical_tick',
    'SNAPSHOT_FORMAT_VERSION',
    'start_action',
    'STATE_DOMAIN_ID_PATTERN',
    'STRUCTURAL_EFFECT_TYPES',
    'take_due',
    'TimePolicy',
    'TIMESTAMP_METADATA_KEY',
    'TimestampStrategy',
    'TRANSACTION_REFERENCE_ISSUE_KINDS',
    'transition_action',
    'UnknownActionError',
    'UnknownConditionError',
    'validate_timing',
    'VALIDATION_ISSUE_KINDS',
    'ScenarioState',
    'ScheduledEntryId',
    'ScheduledEvent',
    'SetScenarioDataPayload',
    'SetWorldVariablePayload',
    'Snapshot',
    'SyncTrigger',
    'StateDomainId',
    'StateDomainTarget',
    'TraceKind',
    'TraceRecord',
    'TraceRecordId',
    'Transaction',
    'TransactionId',
    'TransactionStatus',
    'TriggerConflictError',
    'TriggerRegistry',
    'ValidationError',
    'ValidationContext',
    'ValidationIssue',
    'ValidationPipeline',
    'ValidationReport',
    'WakeupHook',
    'WakeupHookRegistry',
    'WorldState',
    'WriteBarrier',
    'WriteBarrierError',
    'abort_transaction',
    'ActorDecisionContext',
    'ActorUnknownError',
    'apply_committed_effects',
    'apply_mode_change',
    'apply_transaction',
    'assert_json_clean',
    'Capability',
    'CapabilityGrant',
    'CapabilityTable',
    'CapabilityScopeError',
    'Belief',
    'BeliefKind',
    'BehaviorPolicy',
    'check_authority',
    'check_capability',
    'check_effect_id_kinds',
    'check_snapshot_versions',
    'check_transaction_references',
    'commit_transaction',
    'conflict_key',
    'conflicts_with',
    'decode_observations',
    'decode_knowledge',
    'decode_spaces',
    'ContextBuildInput',
    'ContextProvider',
    'ContextInvariantError',
    'deep_copy_via_roundtrip',
    'default_handler_registry',
    'DEFAULT_NPC_CAPABILITIES',
    'DefaultContextProvider',
    'DefaultModePolicy',
    'detect_conflicts',
    'dump_json',
    'effect_locks',
    'encode_observations',
    'encode_knowledge',
    'encode_spaces',
    'entity_domain_positions',
    'extract_effect_locks',
    'freeze_view',
    'GraphSpace',
    'GridSpace',
    'guard',
    'INF_DISTANCE',
    'install_write_barrier',
    'InvalidPositionError',
    'is_action_available',
    'is_guarded',
    'is_stale',
    'KnowledgeState',
    'KNOWLEDGE_COMPONENT',
    'load_json',
    'make_backend',
    'match_selector',
    'MEMORY_COMPONENT',
    'ModeInvariantError',
    'ModeOperation',
    'ModeOperationKind',
    'ModeOverlay',
    'ModeOverlayRegistry',
    'ModeChangeRequest',
    'ModeChangeResolution',
    'MergedModeConfiguration',
    'merge_modes',
    'ModePolicy',
    'new_action_instance_id',
    'new_cascade_id',
    'new_effect_id',
    'new_entity_id',
    'new_event_id',
    'new_observation_id',
    'new_scheduled_entry_id',
    'new_trace_record_id',
    'new_transaction_id',
    'next_revision',
    'ObservationRecord',
    'OBSERVATIONS_COMPONENT',
    'parse_action_type_id',
    'parse_component_type_id',
    'parse_effect_type_id',
    'parse_event_type_id',
    'parse_id',
    'parse_state_domain_id',
    'PlayerPolicy',
    'PolicyActorMismatchError',
    'restore_snapshot',
    'resolve_conflicts',
    'SpacePosition',
    'SpatialDomain',
    'SPATIAL_BACKEND_KINDS',
    'SpaceBackend',
    'SpaceRegistry',
    'SpaceMapping',
    'SPACES_COMPONENT',
    'SpaceInvariantError',
    'run_policy_decide',
    'state_create_entity',
    'state_remove_component',
    'state_remove_entity',
    'state_remove_world_variable',
    'state_set_component',
    'state_set_scenario_state',
    'state_set_world_variable',
    'uninstall_write_barrier',
    'UnknownDomainError',
    'UnknownBackendError',
    'UnknownModeError',
    'validate_proposed_effect',
    'write_barrier_exempt',
    'write_barrier_installed',
]


